### ISSUE TITLE
naersk rewrites `Cargo.toml` to something unparseable

### ISSUE THREAD

**Issue by GoldsteinE** [nix-community/naersk#263]
I tried to install `dylint` with these packages:

```nix
(naersk'.buildPackage {
  root = dylint;  # where `dylint` is a flake input pointing to `github:trailofbits/dylint/v2.0.12`
  cargoBuildOptions = x: x ++ [ "-p" "cargo-dylint" ];
  cargoTestOptions = x: x ++ [ "-p" "cargo-dylint" ];
})
(naersk'.buildPackage {
  root = dylint;
  cargoBuildOptions = x: x ++ [ "-p" "dylint-link" ];
  cargoTestOptions = x: x ++ [ "-p" "dylint-link" ];
})
```

I get this error:

```
error: failed to parse manifest at `/build/dummy-src/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  TOML parse error at line 3, column 39
    |
  3 | metadata = { dylint = { libraries = [ {"path":"examples/*/*"} ] } }
    |                                       ^
  Unexpected `{`
  Expected `]`
```

Indeed, TOML in `dummy-src` looks like this:

```toml
[workspace]
members = [ "cargo-dylint", "dylint", "dylint-link", "internal", "utils/linting", "utils/testing" ]
metadata = { dylint = { libraries = [ {"path":"examples/*/*"} ] } }
```

While the actual TOML from the repo is correct:

```toml
# smoelius: `dylint_driver` is in its own workspace because it requires specific Rust components.

[workspace]
members = [
    "cargo-dylint",
    # "driver",
    "dylint",
    "dylint-link",
    "internal",
    "utils/linting",
    "utils/testing",
]

[workspace.metadata.dylint]
libraries = [
    { path = "examples/*/*" },
]
```

**Comment by GoldsteinE** [comment]
It seems like this is the bug: it’s incorrect to just `toJSON` every val in list of attrs. The correct output should probably be

```
[[workspace.metadata.dylint.libraries]]
path = "examples/*/*"
```

**Comment by Patryk27** [comment]
I see - thanks for investigating, I'll try fixing it 🙂

**Comment by GoldsteinE** [comment]
As implementing full TOML serializer in Nix is complicated and further bugs may arise, maybe there is value in providing `usePureToTOML = false;` option to use external TOML serializer?

**Comment by Xe** [comment]
I ran into this too:

```toml
[package.metadata.generate-rpm]
assets = [
  { source = "target/release/xn--ts9h", dest = "/usr/bin/🥺", mode = "6755"},
  { source = "README.md", dest = "/usr/share/doc/🥺/README", mode = "644", doc = true},
  { source = "LICENSE", dest = "/usr/share/doc/🥺/LICENSE", mode = "644", doc = true},
  { source = "🥺.8", dest = "/usr/share/man/man8/🥺.8", mode = "644", doc = true},
]
```

Amazingly the emoji is NOT the issue!

**Comment by Pegasust** [comment]
Chiming in to the issue train, this is preventing us from compiling Leptos (in a workspace):

Original

```toml
[[workspace.metadata.leptos]]
## Workspace config
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle
name = "proto"
# Executable for the webserver
bin-package = "proto-web"
lib-package = "proto-front"
# ...
```

Processed:

```toml
 metadata = { leptos = [ {"assets-dir":"public","bin-default-features":false,"bin-features":["ssr"],"bin-package":"huawei-pro
to-web","browserquery":"defaults","end2end-cmd":"npx playwright test","env":"DEV","lib-default-features":false,"lib-features":["hydrate"],"
lib-package":"huawei-proto-front","name":"huawei-proto","reload-port":3001,"site-addr":"127.0.0.1:3000","site-pkg-dir":"pkg","site-root":"t
arget/huawei-proto","tailwind-config-file":"./frontend/huawei-proto-front/tailwind.config.js","tailwind-input-file":"./frontend/huawei-prot
o-front/tailwind.css"} ] }
```

I'm relatively new to the codebase. Why are we having a rewriting of `Cargo.toml`?
