### ISSUE TITLE
[lib] is not copied over

### ISSUE THREAD

**Issue by rbozan** [nix-community/naersk#269]
Related to https://github.com/nix-community/naersk/issues/263

Having a Cargo.toml like the following:
```toml
[package]
name = "scenario"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"] #, "lib"]

[dependencies]
scenario_builder = { git = "ssh://git@gitlab.com/l4010/scenario_builder.git", features = ["build-scenario"] }
tokio = { version = "1.17.0", features = [ "macros" ] }
anyhow = "1.0.66"

sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "mysql" ] }
```

However looking in `dummy-src` the Cargo.toml now suddenly is:

```toml
[dependencies]
anyhow = "1.0.66"
"scenario_builder" = { features = [ "build-scenario" ], git = "ssh://git@gitlab.com/l4010/scenario_builder.git" }
sqlx = { features = [ "runtime-tokio-rustls", "mysql" ], version = "0.5" }
tokio = { features = [ "macros" ], version = "1.17.0" }
[package]
edition = "2021"
name = "scenario"
version = "0.1.0"
```

Removing the "crate-type", which would then build a ".so" file but a ".rlib" file.
