### ISSUE TITLE
building single crate from a workspace fails on a 2nd crate?

### ISSUE THREAD

**Issue by i-am-logger** [nix-community/naersk#336]
![image](https://github.com/user-attachments/assets/485f543d-3e70-41bc-b563-cb081d42cb39)
the cargo.toml of the crate i'm buding has no dependencies on `candle-core`

```toml
[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
twelf.workspace = true
url.workspace = true
utoipa.workspace = true
utoipa-axum.workspace = true
utoipa-redoc.workspace = true
utoipa-swagger-ui.workspace = true

```
